blog/urls.py
from django.urls import path, include

from .views import *


urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('category/<slug:cat_slug>/', CategoryListView.as_view(), name='category'),
    path('search/', SearchView.as_view(), name='search'),
    path('post_new/', EditCreatePostView.as_view(), name='post_new'),
    path('post/<slug:post_slug>/', PostDetailView.as_view(), name='post_detail'),
    path('post/<slug:post_slug>/edit/', EditCreatePostView.as_view(), name='post_edit'),
    path('post/<slug:post_slug>/comment_add/', AddCommentView.as_view(), name='comment_add'),
    path('post/<slug:post_slug>/comment_edit/<int:pk>/', comment_edit, name='comment_edit'),
    path('post/<slug:post_slug>/comment/<int:comment_pk>/answer/',
        AnswerForCommentView.as_view(),
        name='comment_answer'
    ),
]

mysite/urls.py
from django.conf.urls import handler404, handler500
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('cats/', include('cats.urls'), name='cats_list'),
    path('dogs/', include('dogs.urls'), name='dogs_list'),
    path('users/', include('users.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'mysite.views.page_not_found_view'
handler500 = 'mysite.views.page_500'

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import get_user_model


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='URL')
    text = models.TextField(help_text='Напишите что-нибудь..', verbose_name='Текст')
    create_date = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    published_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, 
        null=True, blank=True, related_name='posts', verbose_name='Категория'
    )

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'post_slug': self.slug})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name='Пост'
        verbose_name_plural='Посты'
        ordering=['-create_date', 'title']


class Comment(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Автор')
    post = models.ForeignKey('Post', on_delete=models.CASCADE, verbose_name='Пост')
    text = models.TextField(max_length=300, verbose_name='Текст комментария')
    create_date = models.DateTimeField(default=timezone.now, verbose_name='Дата создания')
    edit_date = models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего изменения')
    comment = models.ForeignKey(
        'self', on_delete=models.CASCADE, related_name='comments',
        blank=True, null=True, verbose_name='Комментарий к комментарию'
    )

    def __str__(self):
        return f'{self.author}'

    class Meta:
        ordering = ['-create_date', 'author']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Category(models.Model):
    name = models.CharField(max_length=35, verbose_name='Имя категории')
    slug = models.SlugField(unique=True, verbose_name='URL')

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        

blog/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'slug', 'text', 'category')
        prepopulated_fields = {'slug': ('title',)}


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

blog/views.py
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, FormView
from django.utils import timezone

from .models import Post, Comment, Category
from .forms import PostForm, CommentForm


class PostListView(ListView):
    model = Post
    paginate_by = 2
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_selected'] = 0
        return context

    def get_queryset(self, **kwargs):
        return Post.objects.all().select_related('author', 'category')


class CategoryListView(PostListView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat_selected'] = self.kwargs['cat_slug']
        return context

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['cat_slug']).select_related('author', 'category')
    

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = kwargs['object'].comment_set.all().prefetch_related('author', 'comments__author')
        return context

    def get_object(self, queryset=None):
        return Post.objects.filter(slug=self.kwargs.get('post_slug')).select_related('author', 'category').get()


class EditCreatePostView(LoginRequiredMixin, View):
    template_name_edit = 'blog/post_edit.html'
    template_name_create = 'blog/post_new.html'

    def get(self, request, post_slug=None):
        if post_slug:
            post = get_object_or_404(Post, slug=post_slug)
            form = PostForm(instance=post)
            return render(request, self.template_name_edit, {'form': form})
        else:
            form = PostForm()
            return render(request, self.template_name_create, {'form': form})

    def post(self, request, post_slug=None):
        if post_slug:
            post = get_object_or_404(Post, slug=post_slug)
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.published_date = timezone.now()
                post.save()
                return redirect(post.get_absolute_url())
            return render(request, self.template_name_edit, {'form': form})
        else:
            form = PostForm(request.POST)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.published_date = timezone.now()
                post.save()
                return redirect(post.get_absolute_url())

            return render(request, self.template_name_create, {'form': form})
        

@login_required
def comment_edit(request, pk, post_slug=None):
    comment = get_object_or_404(Comment, pk=pk)
    form = CommentForm(instance=comment)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.edit_date = datetime.now()
            comment.save()
            return redirect('post_detail', post_slug=post_slug)
    return render(request, 'blog/comment_edit.html', {'form': form})


class SearchView(View):
    template_name = 'blog/search.html'

    def get(self, request):
        query = request.GET['q']
        categories = request.GET.getlist('category')
        if not(query.isspace() or query == ''):
            if categories:
                posts = Post.objects.filter(
                    title__icontains=query, 
                    category__name__in=categories
                )
            else:
                posts = Post.objects.filter(title__icontains=query)
        else:
            posts = None
        context = {
            'posts': posts,
            'query': query,
            'categories': categories
        }
        return render(request, self.template_name, context)


class AddCommentView(LoginRequiredMixin, FormView):
    template_name = 'blog/comment_add.html'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = Post.objects.filter(slug=self.kwargs['post_slug']).select_related('author').get()
        return context

    def form_valid(self, form):
        form = form.save(commit=False)
        form.author = self.request.user
        form.post = Post.objects.get(slug=self.kwargs['post_slug'])
        form.create_date = datetime.now()
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('post_detail', kwargs={'post_slug': self.kwargs['post_slug']})


class AnswerForCommentView(LoginRequiredMixin, View):
    template_name = 'blog/comment_answer.html'

    def get(self, request, post_slug, comment_pk):
        comment = Comment.objects.get(pk=comment_pk)
        form = CommentForm()
        context = {
            'comment': comment,
            'form': form
        }
        return render(request, self.template_name, context)

    def post(self, request, post_slug, comment_pk):
        form = CommentForm(request.POST)
        post = Post.objects.get(slug=post_slug)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.comment = Comment.objects.get(pk=comment_pk)
            comment.create_date = datetime.now()
            comment.save()
            return redirect(post.get_absolute_url())
        return render(request, self.template_name, {'form': form})


# def post_list(request):
#     posts = Post.objects.all()
#     return render(request, 'blog/post_list.html', {'posts': posts})


# def post_new(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.published_date = timezone.now()
#             post.save()
#             return redirect('post_detail', pk=post.pk)
#     else:
#         form = PostForm()
#     return render(request, 'blog/post_new.html', {'form': form})


# def post_edit(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     form = PostForm(instance=post)
#     if request.method == 'POST':
#         form = PostForm(request.POST, instance=post)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.published_date = timezone.now()
#             post.save()
#             return redirect('post_detail', pk=post.pk)
#     return render(request, 'blog/post_edit.html', {'form': form})


# def post_detail(request, post_slug):
#     post = get_object_or_404(Post, slug=post_slug)
#     comments = post.comment_set.filter(comment=None)
#     if request.method == 'POST':
#         form_comment = CommentForm(request.POST)
#         if form_comment.is_valid():
#             comment = form_comment.save(commit=False)
#             comment.author = request.user
#             comment.post = post
#             comment.create_date = datetime.now()
#             comment.save()
#     form_comment = CommentForm()  
#     return render(request, 'blog/post_detail.html', {
#         'post': post, 
#         'comments': comments, 
#         'form_comment': form_comment
#         })

blog/templates/blog/base.html
{% load static %}
{% load blog_categories %}

<!DOCTYPE html>
<html lang="ru">    
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'blog/img/main.ico' %}">
    <title>Django Girls Blog</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bonheur+Royale&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
</head>
<body>
    <header class="header">
        <div class="container">
            <h1 class="header-title"><a href="/">Django Girls Blog!</a></h1>
            <ul class="header-menu">
                {% block header_menu %}
                    <li><a href="/">Наши посты</a></li>
                    <li><a href="{% url 'cats_list' %}">Наши коты</a></li>
                    <li><a href="{% url 'dogs_list' %}">Наши пёсели</a></li>
                {% endblock %}
            </ul>
            <div class="auth-menu">
                {% if user.is_authenticated %}
                    <p class="username">Привет, <a href="{% url 'profile' %}" class="profile-ref login">{{ user }}</a><br>
                        <a href="{% url 'logout' %}" class="logout">Выйти</a>
                    </p>
                    
                {% else %}
                    <p class="username">Вы не аутентифицированы,
                        <br>пожалуйста <a href="{% url 'login' %}" class="login">войдите</a><br>
                        или <a href="{% url 'registration' %}" class="registration">зарегестрируйтесь</a>
                    </p>
                {% endif %}
            </div>
            {% search_form query %}
        </div>
    </header>

    <section class="content">
        <div class="container">
            {% list_blog_categories cat_selected %}

            {% block content %}
            {% endblock %}
        </div>
    </section>

    <footer class="footer">
        <div class="container">
            <div class="footer-addres">
                <img src="{% static 'blog/img/rub.png' %}" alt="rub">
                <p class="addres">
                    <a href="https://goo.gl/maps/ZZxd8QJaisueW2ZaA" target="_blank">109012, г. Москва, Кремль-9, 
                        ФСО России - почтовый 123022, 
                        г. Москва, ул. Красная Пресня, 44, стр. 2</a>
                </p>
            </div>
            
            <div class="footer-menu">
                <p>Что ты хочешь?</p><br>
                <ul class="menu">
                    <li><a href="{% url 'cats_list' %}">Котики</a></li>
                    <li><a href="{% url 'dogs_list' %}">Песики</a></li>
                    <li><a href="{% url 'post_list' %}">Посты</a></li>
                    <li><a href="{% url 'all_users' %}">Все пользователи</a></li>
                    <li><a href="/">Рыбка</a></li>
                </ul>
            </div>
            <div class="footer-menu footer-menu-2">
                <p>Еще есть такое</p><br>
                <ul class="menu">
                    <li><a href="/">Диван</a></li>
                    <li><a href="/">Кот на диване</a></li>
                    <li><a href="/">Окно</a></li>
                    <li><a href="/">Человек</a></li>
                    <li><a href="/">Холодильник</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>
</html>

blog/templates/blog/comment_add.html
{% extends 'blog/base.html' %}


{% block content %}
<div class="post">
    {% if post.published_date %}
        <div>
            <p>Дата публикации: {{ post.published_date }}</p>
        </div>
    {% endif %}
    <p class="post-author">Автор поста: <a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a></p>
    <h3 class="post-title">{{ post.title }}</h3>
    <p class="post-text">{{ post.text|linebreaksbr }}</p>
    {% if user.is_authenticated %}
        <a href="{% url 'post_edit' post_slug=post.slug %}" class="btn btn-post-edit">Редактировать</a>
    {% endif %}
    <a href="{% url 'post_list' %}" class="btn btn-back"></a>
    <p class="post-category">Категория: <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></p>
</div>

<div class="comments">
    <h4 class="comments-title">Комментарий</h4>
    <form action="" method="POST" class="comment-form">{% csrf_token %}
        {% for f in form %}
            <div class="{{ f.name }}">{{ f }}</div>
        {% endfor %}
        <button type="submit" class="comment-create">Добавить комментарий</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/comment_answer.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="comments">
    <h4 class="comments-title">Комментарий</h4>
    <form action="" method="POST" class="comment-form">{% csrf_token %}
        {% for f in form %}
            <div class="{{ f.name }}">{{ f }}</div>
        {% endfor %}
        <button type="submit" class="comment-create">Ответить на комментарий</button>
    </form>
        <div class="comment">
            <p class="comment-create-date">Дата написания: {{ comment.create_date }}</p>
            {% if comment.edit_date %}
                <p class="comment-edit-date">Отредактировано: {{ comment.edit_date }}</p>
            {% endif %}
            <p class="comment-author">Автор: 
                <a href="{{ comment.author.get_absolute_url }}">{{ comment.author }}</a>
            </p>
            <hr>
            <p class="comment-text">{{ comment.text }}</p>

            
        </div>
        
    
</div>
{% endblock %}

blog/templates/blog/comment_edit.html
{% extends 'blog/base.html' %}


{% block content %}
    <div class="comment-edit">
        <form action="" method="POST" class="comment-form">{% csrf_token %}
            {% for f in form %}
                <div class="{{ f.name }}">{{ f }}</div>
            {% endfor %}
            <button type="submit" class="btn btn-comment-save">Сохранить</button>
        </form>
        
    </div>
{% endblock %}

blog/templates/blog/comments.html
<hr>
<div class="comments">
    <h4 class="comments-title">Комментарии</h4>

    {% if user.is_authenticated %}
        <a href="{% url 'comment_add' post_slug=post.slug %}" class="comment-create">Добавить комментарий</a>
    {% else %}
        <a href="{% url 'login' %}" class="comment-create">Необходимо авторизироваться</a>
    {% endif %}

    
    {% for comment in comments %}
        <div class="comment">
            <p class="comment-create-date">Дата написания: {{ comment.create_date }}</p>
            {% if comment.edit_date %}
                <p class="comment-edit-date">Отредактировано: {{ comment.edit_date }}</p>
            {% endif %}
            <p class="comment-author">Автор: 
                <a href="{{ comment.author.get_absolute_url }}">{{ comment.author }}</a>
            </p>
            <hr>
            <p class="comment-text">{{ comment.text }}</p>
            {% if user == comment.author %} 
                <a href="{% url 'comment_edit' post_slug=post.slug pk=comment.pk %}" class="comment-edit">Изменить</a>
            {% endif %}
            {% if user.is_authenticated %}
                <a href="{% url 'comment_answer' post_slug=post.slug comment_pk=comment.pk %}">Ответить</a>
            {% else %}
                <a href="{% url 'login' %}">Авторизируйтесь чтобы ответить</a>
            {% endif %}
        </div>
            {% for subcomment in comment.comments.all %}
                
                <div class="comment subcomment">
                    <p class="comment-create-date">Дата написания: {{ subcomment.create_date }}</p>
                    {% if subcomment.edit_date %}
                        <p class="comment-edit-date">Отредактировано: {{ subcomment.edit_date }}</p>
                    {% endif %}
                    <p class="comment-author">Автор: 
                        <a href="{{ comment.author.get_absolute_url }}">{{ subcomment.author }}</a>
                    </p>
                    <p class="comment-author"> Ответ на комментарий
                        <a href="">{{ comment }}</a>
                    </p>
                    <hr>
                    <p class="comment-text">{{ subcomment.text }}</p>
                    {% if user == subcomment.author %} 
                        <a href="{% url 'comment_edit' post_slug=comment.post.slug pk=subcomment.pk %}" class="comment-edit">Изменить</a>
                    {% endif %} 
                </div>
                
            {% endfor %}
    {% endfor %}
</div>

blog/templates/blog/form_post.html
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/admin/js/core.js"></script>
<script src="/static/admin/js/urlify.js"></script>
<script src="/static/admin/js/prepopulate.js"></script>
{% for f in form %}
    {{ f.label_tag }}
    <div class="form-post-{{ f.name }}">{{ f }}</div>
    <br>
{% endfor %}
<script id="django-admin-prepopulated-fields-constants" 
        src="/static/admin/js/prepopulate_init.js" 
        data-prepopulated-fields="[{
            &quot;id&quot;: &quot;#id_slug&quot;, 
                &quot;name&quot;: &quot;slug&quot;, 
                &quot;dependency_ids&quot;: [&quot;#id_title&quot;], 
                &quot;dependency_list&quot;: [&quot;title&quot;], 
                &quot;maxLength&quot;: 200, 
                &quot;allowUnicode&quot;: false
            }]">
</script>

blog/templates/blog/list_categories_tag.html
<div class="categories">
    <ul>
        <h3 class="categories-title">Категории</h3>
        <hr>
        {% if cat_selected == 0 %}
            <li><a href="{% url 'post_list' %}" class="selected">Все категории</a></li>
        {% else %}
            <li><a href="{% url 'post_list' %}">Все категории</a></li>
        {% endif %}
        {% for cat in categories %}
            {% if cat_selected == cat.slug %}
                <li><a href="{{ cat.get_absolute_url }}" class="selected">{{ cat }}</a></li>
            {% else %}
                <li><a href="{{ cat.get_absolute_url }}">{{ cat }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block header_menu %}
    <li><a href="{% url 'cats_list' %}">Наши коты</a></li>
    <li><a href="{% url 'dogs_list' %}">Наши пёсели</a></li>
{% endblock %}

{% block content %}
<div class="post">
    {% if post.published_date %}
        <div>
            <p>Дата публикации: {{ post.published_date }}</p>
        </div>
    {% endif %}
    <p class="post-author">Автор поста: <a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a></p>
    <h3 class="post-title">{{ post.title }}</h3>
    <p class="post-text">{{ post.text|linebreaksbr }}</p>
    {% if user.is_authenticated %}
        <a href="{% url 'post_edit' post_slug=post.slug %}" class="btn btn-post-edit">Редактировать</a>
    {% endif %}
    <a href="{% url 'post_list' %}" class="btn btn-back"></a>
    <p class="post-category">Категория: <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></p>
    {% include 'blog/comments.html' %}
</div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block header_menu %}
    <li><a href="{% url 'cats_list' %}">Наши коты</a></li>
    <li><a href="{% url 'dogs_list' %}">Наши пёсели</a></li>
{% endblock %}

{% block content %}
<div class="post">
    <h3 class="post-title">Редактировать пост</h3>
    {% include 'registration/errors_msg.html' %}
    <form action="" method="POST" class="form-post">{% csrf_token %}
        {% include 'blog/form_post.html' %}
        <button type="submit" class="form-save btn">Сохранить</button>
        <a href="/" class="btn btn-back"></a>
    </form> 
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block header_menu %}
    <li><a href="{% url 'cats_list' %}">Наши коты</a></li>
    <li><a href="{% url 'dogs_list' %}">Наши пёсели</a></li>
{% endblock %}

{% block content %}
<div class="content-title">
    <h2>Наши посты!</h2>
</div>
    {% if user.is_authenticated %}
        <a href="{% url 'post_new' %}" class="create-new-post">
            ДОБАВИТЬ ПОСТ
        </a>
    {% endif %}
    {% for post in posts %}
    <div class="post">
        <h3 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
        <p class="post-text">{{ post.text|linebreaksbr }}</p>
        <p class="post-date">Дата создания: {{ post.create_date }}</p>
        <p class="post-author">Автор поста: <a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a></p>
        <p class="post-category">Категория: <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></p>
    </div>
    {% endfor %}

    {% if page_obj.paginator.num_pages > 1 %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                {% if page_obj.previous_page_number != 1 %}
                    <a href="?page={{ 1 }}">1 </a>
                    {% if page_obj.previous_page_number|add:-1 != 1 %}
                        <span>...</span> 
                    {% else %}
                        <span>,</span>
                    {% endif %}
                {% endif %}
                <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                <span>,</span>
            {% endif %}

            <span class="current">{{ page_obj.number }}</span>

            {% if page_obj.has_next %}
                <span>,</span>
                <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                    {% if page_obj.next_page_number|add:1 != page_obj.paginator.num_pages %}
                        <span>...</span>
                    {% else %}
                        <span>,</span>
                    {% endif %}
                    <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
                {% endif %}
            {% endif %}
        </span>
    </div>
    {% endif %}
{% endblock %}

blog/templates/blog/post_new.html
{% extends 'blog/base.html' %}

{% block header_menu %}
    <li><a href="{% url 'cats_list' %}">Наши коты</a></li>
    <li><a href="{% url 'dogs_list' %}">Наши пёсели</a></li>
{% endblock %}

{% block content %}
    <div class="post">
        <h3 class="post-title">Новый пост</h3>
        {% include 'registration/errors_msg.html' %}
        <form action="" method="POST" class="form-post">{% csrf_token %}
            {% include 'blog/form_post.html' %}
            <button type="submit" class="form-save btn">Сохранить</button>
            <a href="/" class="btn btn-back"></a>
        </form> 
    </div>
{% endblock %}

blog/templates/blog/search.html
{% extends 'blog/base.html' %}


{% block content %}
    <div class="registration">
        {% if posts %}
            <h1 class="registration-header">{{ posts|length }} результата поиска по запросу: {{ query }}</h1>
            {% if categories %}
                <h1 class="registration-header">По категориям: {{ categories|join:", " }}</h1>
            {% else %}
                <h1 class="registration-header">По всем категориям</h1>
            {% endif %}
            {% for post in posts %}
                <div class="post">
                    <h3 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h3>
                    <p class="post-text">{{ post.text|linebreaksbr }}</p>
                    <p class="post-date">Дата создания: {{ post.create_date }}</p>
                    <p class="post-author">Автор поста: <a href="{{ post.author.get_absolute_url }}">{{ post.author }}</a></p>
                    <p class="post-category">Категория: <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></p>
                </div>
            {% endfor %}
        {% else %}
            <h1 class="registration-header">По вашему запросу {{ query }} ничего не найдено:(</h1>
        {% endif %}
    </div>
{% endblock %} %}

blog/templates/blog/search_form_tag.html
<div class="search">
    <form action="{% url 'search' %}" method="get">
        <input type="search" class="search-inp" name="q" placeholder="Ищите пост" value="{{ query }}">
        <span class="category-hidden">Выбрать категорию
                <!-- <label><input type="checkbox" name="category" id="1" value="all">Все категории</label> -->
                <div>
                    {% for cat in categories %}
                    <label><input type="checkbox" name="category" value="{{ cat }}">{{ cat }}</label>
                    {% endfor %}
                </div>
        </span>
        <button type="submit" class="btn">Искать</button>
    </form>
</div>